### ISSUE TITLE
The word "Independent" is spelled wrong in the search results

### ISSUE THREAD

**Issue by ghost** [climatecabinet/scorecard-search#37] opened 2021-08-24 15:30 UTC
Expected:
- Independent

Current:
-Shows "Indepenent" (missing second d)

Steps for replication: 
1. Use the search feature to find Minnesota Senate District 3 (Thomas Bakk)

**Comment by mherrero347** [comment] 2021-08-25 19:37
This is actually a duplicate of [a database repo issue](https://github.com/climatecabinet/climatecabinet/issues/63) which has already been patched and will be fixed in the next db deployment.

**Closed as completed by mherrero347** 2021-08-25 19:37 UTC
Labels: duplicate
